### ISSUE TITLE
Error when invalid credentials used

### ISSUE THREAD

**Issue by mullinscr** [mullinscr/c2_plugin_issues#33]
**Describe the bug**
Sometimes, when the cookies have been reset via the browser, the plugin still "thinks" that it is using a valid session. But it is not, so when the user tries to 

**To Reproduce**
1. Get a valid session cookie and set it in the settings
2. Check everything is working as expected
3. In the browser, logout and then log back in to C2
4. Now in QGIS try a new plugin action (e.g. get sites) and an error will be thrown

**Expected behavior**
No error thrown - a message to the user that they may need to refresh their credentials.

**Additional context**

```python
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
Traceback (most recent call last):
  File "C:/Users/cmullins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\c2\c2_plugin.py", line 179, in load_sites
    sites = get_sites()
  File "C:/Users/cmullins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\c2\c2_api.py", line 229, in get_sites
    sites = c2.get_filtered_sites_data()
  File "C:/Users/cmullins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\c2\c2_api.py", line 105, in get_filtered_sites_data
    return json.loads(resp.content)['data']
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mullinscr** [comment]
Perhaps - do a credential check before any operation that requires the API? And raise a warning message if doesn't pass?
